name: learn-github-actions
run-name: ${{github.actor}} is learning Github actions
on: 
  push:
    branches:
      - main
  release:
    types:
      - published
    paths:
      - 'new_utils/**'
env:
  DAY_OF_WEEK: Monday
jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.tag }}
    steps:
      - name: Get the version
        id: vars
        run: echo "tag=$(echo ${GITHUB_REF/refs\/tags\//} | awk -F_ '{print $NF}')" >> $GITHUB_OUTPUT
  test_env:
    needs:
      - calculate-version
    runs-on: ubuntu-latest
    env: 
      WEEK_OF_MONTH: 4
    steps:
      - name: Step 1
        env: 
          NAME: "sriram"
        run: echo "$DAY_OF_WEEK and the week is $WEEK_OF_MONTH and name is $NAME"
      - name: Step 2
        run: echo "Building and releasing version ${{ needs.calculate-version.outputs.version }}"
      - name: step 3
        run: echo "What this is inside is the event ${{github.event_name}}"
      - name: step 4
        run: echo "Building and releasing version ${{ needs.calculate-version.outputs.version }}"
  test_env2:
    runs-on: ubuntu-latest
    steps:
      - name: env2 step1
        run: echo "$DAY_OF_WEEK and the week is $WEEK_OF_MONTH and name is $NAME"

        
          
      


