name: learn-github-actions
run-name: ${{github.actor}} is learing Github actions
on: 
  push:
    branches:
      - main
jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
      - env:
          ISSUE_URL: "hello sriram"
        run: |
          echo ${{ISSUE_URL}}
      


