name: learn-github-actions
run-name: ${{github.actor}} is learing Github actions
on: 
  push:
    branches:
      - main
env:
  DAY_OF_WEEK: Monday
jobs:
  test_env:
    runs-on: ubuntu-latest
    env: 
      WEEK_OF_MONTH: 4
    steps:
      - name: step 1
        run: echo "$DAY_OF_WEEK and the week is $WEEK_OF_MONTH and name is $NAME"
        env: 
          NAME: "sriram"
          
      


