name: learn-github-actions
run-name: ${{github.actor}} is learning Github actions
on: 
  push:
    tags:
      - batch_service_v*
env:
  DAY_OF_WEEK: Monday
jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.tag }}
    steps:
      - name: Get the version
        id: vars
        run: echo "tag=$(echo ${GITHUB_REF/refs\/tags\//})" >> $GITHUB_OUTPUT
  test_env:
    runs-on: ubuntu-latest
    env: 
      WEEK_OF_MONTH: 4
    steps:
      - name: Step 1
        env: 
          NAME: "sriram"
        run: echo "$DAY_OF_WEEK and the week is $WEEK_OF_MONTH and name is $NAME"
      - name: Step 2
        run: echo "$DAY_OF_WEEK and the week is $WEEK_OF_MONTH and name is $NAME"
  test_env2:
    runs-on: ubuntu-latest
    steps:
      - name: env2 step1
        run: echo "$DAY_OF_WEEK and the week is $WEEK_OF_MONTH and name is $NAME"

        
          
      


