name: learn-github-actions
run-name: ${{github.actor}} is learing Github actions
on: 
  push:
    branches:
      - main
jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: "hello sriram"
        run: |
          echo ${{GITHUB_TOKEN}}
      


